# Single-file compilation of the original author's coding efforts for the model

Attempting to use a tooltip.

This test will show how tooltips redner in Jupyter itself, and in Github once this notebook is uploaded.

*Example*: <span title="Your tooltip text here">Hover over me</span>


<u>Tooltips of increasing length</u>
* We will re-use this line: "Single-file compilation of original author's coding efforts for the model"
* it is 10-words total.

---
* After testing, using chained repetitions of the 10-word line above, we fit $136$ words into 1 tooltip.
* This amounted to $1018$ characters as one line (no newline etc) **with** spaces
* This amounted to $883$ characters as onel line (no newlines etc) ***without** considering spaces


10 words: <span title="Single-file compilation of original author's coding efforts for the model">Hover over me</span>

100 words: <span title="Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model[100]">Hover over me</span>

200 words: <span title="Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model[100] Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model Single-file compilation of original author's coding efforts for the model[100]">Hover over me</span>

# I - PD_IFRS.ipynb

# II - PD_Model.txt

# III - Credit Risk.ipynb

NOTE : We've replaced the mostly empty loan dtaa file from the original repository with a similar file (same LendingClub source).

As such, the results for this file will differ from the results for the ones below, when we still relied on the original sample loan data file.

Above, meaning file preceding this one, should also use the newly souce loan data ($1.1 GB$). These files were investgated from bottom to top.

# IV - Credit Risk 2.ipynb

### Outline

#### [ ] install numpy and import pandas

#### [ ] read the loan data into 2 different variables

#### [ ] this loan data had 75 columns, we display the column names

#### [ ] check df.head , and df.info

#### [ ] check if certain continuous vars hold numerics, and check dates
- ##### emp_length
- ##### earlist_cr_line
- ##### earlist_cr_line_date

#### [ ] create calculated time between credit lines

####

<p style="font-family:Nunito;font-size:20px;">
    NOTE : We've replaced the mostly empty loan dtaa file from the original repository with a similar file (same LendingClub source).

As such, the results for this file will differ from the results for the ones below, when we still relied on the original sample loan data file.

Above, meaning file preceding this one, should also use the newly souce loan data ($1.1 GB$) and $2,260,668$ rows. These files were investgated from bottom to top.
</p>

$\downarrow ~ \Downarrow ~ \downarrow$

Can we figure out which column is considered to have mixed types?

**NO**

There migth actually be an issue with parsing when we passs directly to read_csv. We will ignore this for now, and just go through the mechanics of the original notebook, using our new data file. Therefore we read in only $100,000$ rows, and continues. Later on we can ddress any parsing issues with the full 1GB file.

In [1]:
# 75 cols used originally - we removed "Unnamed: 0" from the 1st slot
# so it's 74
the75 = ['id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url',
       'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m']

In [2]:
stat_details= {'Current': 919695, 
     'Fully Paid': 1041952, 
     'Late (31-120 days)': 21897, 
     'In Grace Period': 8952, 
     'Charged Off': 261655, 
     'Late (16-30 days)': 3737, 
     'Default': 31, 
     'Does not meet the credit policy. Status:Fully Paid': 1988, 
     'Does not meet the credit policy. Status:Charged Off': 761
     }

In [3]:
sum(stat_details.values())

2260668

In [4]:
full_column_list = ['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'revol_bal_joint',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag',
       'hardship_type', 'hardship_reason', 'hardship_status',
       'deferral_term', 'hardship_amount', 'hardship_start_date',
       'hardship_end_date', 'payment_plan_start_date', 'hardship_length',
       'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status',
       'settlement_date', 'settlement_amount', 'settlement_percentage',
       'settlement_term']

##### Trying to set the column names to a subset, e.g. 75 of the total, leads to import issues.

In [5]:
import pandas as pd

# Set loan file location (Note this is a reative lcoation and will break)
file_path = "../01_data/loan.csv"

pda = pd.read_csv(file_path,
                  #names=the75,
                  nrows=100_000,
                  #low_memory=True)
                  low_memory=False)

In [6]:
len(pda.columns.values)

145

In [7]:
pda.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# illustrates the parsing issue
# Unnamed 0
pda.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
99995,NaN,NaN,2500,2500,2500,36 months,16.91,89.02,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99996,NaN,NaN,8400,8400,8400,36 months,8.46,265.02,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99997,NaN,NaN,16500,16500,16500,60 months,16.91,409.27,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99998,NaN,NaN,20000,20000,20000,36 months,8.46,630.99,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99999,NaN,NaN,8000,8000,8000,36 months,8.46,252.40,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
pda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 145 entries, id to settlement_term
dtypes: float64(58), int64(52), object(35)
memory usage: 110.6+ MB

In [11]:
pda.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,desc,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,0.0,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,0.0,0.0,...,1.0,1.00,1.0,1.0,1.00,1.00,1.00,1.0,1.0,1.0
mean,NaN,NaN,15934.297500,15934.297500,15931.464250,13.004960,462.493739,8.314996e+04,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0
std,NaN,NaN,10146.154617,10146.154617,10148.296023,5.026647,285.647728,1.117613e+05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1000.000000,1000.000000,725.000000,6.000000,30.640000,0.000000e+00,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0
25%,NaN,NaN,8000.000000,8000.000000,8000.000000,8.810000,252.970000,4.784000e+04,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0
50%,NaN,NaN,14000.000000,14000.000000,14000.000000,11.800000,380.810000,6.861300e+04,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0
75%,NaN,NaN,21500.000000,21500.000000,21500.000000,16.140000,622.680000,1.000000e+05,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0
max,NaN,NaN,40000.000000,40000.000000,40000.000000,30.990000,1618.240000,9.757200e+06,NaN,NaN,...,3.0,378.39,3.0,22.0,1135.17,15351.85,1045.41,5443.0,65.0,18.0

In [12]:
pda.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=145)

In [36]:
# all continuous variables must be numeric

pda["emp_length"].unique()

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [37]:
# We can use string replace to convert the emp length to INT values
# remove the end of the string
pda['emp_length_int'] = pda['emp_length'].str.replace(' years','')

In [38]:
pda.emp_length_int.unique()

array(['10+', '6', '4', '< 1 year', '2', '9', nan, '5', '3', '7',
       '1 year', '8'], dtype=object)

In [39]:
# convert less than 1 into a 0
pda['emp_length_int'] = pda['emp_length_int'].str.replace('< 1 year',str(0))

In [40]:
pda.emp_length_int.unique()

array(['10+', '6', '4', '0', '2', '9', nan, '5', '3', '7', '1 year', '8'],
      dtype=object)

In [43]:
# specific conversion for 10+
pda['emp_length_int'] = pda['emp_length_int'].str.replace('+','',regex=False)

In [44]:
pda.emp_length_int.unique()

array(['10', '6', '4', '0', '2', '9', nan, '5', '3', '7', '1 year', '8'],
      dtype=object)

In [45]:
# specific conversion for 1 year
pda['emp_length_int'] = pda['emp_length_int'].str.replace('year','')

In [46]:
pda.emp_length_int.unique()

array(['10', '6', '4', '0', '2', '9', nan, '5', '3', '7', '1 ', '8'],
      dtype=object)

In [48]:
# Now change string numbers into float
pda['emp_length_int'] = pd.to_numeric(pda['emp_length_int'],
                                        errors='coerce')

In [49]:
pda.emp_length_int.unique()

array([10.,  6.,  4.,  0.,  2.,  9., nan,  5.,  3.,  7.,  1.,  8.])

$\uparrow ~ \uparrow ~ \uparrow$

Uses different loan file than below.

# V - Dependent Var Code.txt

In [12]:
# - - - - Full code - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

import pandas as pd # Import pandas for daa handling

# Set your file path to the CSV file on your Desktop
# My edit: --> We use the RAW in Github instead
file_path = "https://raw.githubusercontent.com/QuantVI/"
file_path += "rand_various/refs/heads/main/"
file_path += "Python_PD_LGD_EAD_Modeling/2_original/loan_data.csv"

try:
    # Load the dataset from the specified path
    # My edit --> due to detection of mixed datatypes many columns,
      # we need to turn OFF the low_memory setting.
    df = pd.read_csv(file_path, low_memory=False)
    
    # Create a new binary column 'default' : 1 if risk status, else 0
    # My edit --> create status list first
    bad_statuses = ["Charged Off",
                    "Default",
                    "Late (31-120 days)",
                    "Late (16-30 days)"]
    df['default'] = df['loan_status'].apply(
        lambda x: 1 if x in bad_statuses else 0
    )
    
    # Print the count of defaults (1) vs non-defaults (0)
    print("Default variable distribution:")
    print(df["default"].value_counts())
    
    # Print how many loans fall into each original loan_status category
    print("\nLoan status distribution:")
    print(df["loan_status"].value_counts())

except FileNotFoundError:
    # Message to print if the file path is incorrect or file is missing
    print("File not found. Please check the file path.")

except Exception as e:
    # Catch and print any other unexpected errors
    print(f"An error occurred: {e}")

print(df["loan_status"].value_counts())

Default variable distribution:
0    237722
1         5
Name: default, dtype: int64

Loan status distribution:
Fully Paid     10
Charged Off     5
Current         2
Name: loan_status, dtype: int64
Fully Paid     10
Charged Off     5
Current         2
Name: loan_status, dtype: int64

$\uparrow~\uparrow~\uparrow$  
**My note** :
The results above show that the data is extremely skewed. We have hardly an actual defaults, and no records that are even delinquent. This means very few direct examples of what a defaulter resembles, to learn from.

<font color=magenta>We actually have a major issue with the loan_status column being <b>NaN</b> for 237 710 of 237 727 total values</font>. Its $99.992\%$ blank

The main problem is that the `loan_data.csv` in the original repo was moslty blank and likely not what was intended ot be there. We need a new file for this.

In [34]:
print(df.columns)
print(len(df.columns))

Index(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url',
       'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype='object')
75

$\uparrow~\uparrow~\uparrow$  
<font size=4> We have $75$ total columns </font>

# VI - Split_Train_Test.txt

In [21]:
# My edit to facilitate data import
import pandas as pd
fpath = "https://raw.githubusercontent.com/QuantVI/rand_various/refs/"
fpath += "heads/main/Python_PD_LGD_EAD_Modeling/2_original/loan_data.csv"

df = pd.read_csv(fpath, low_memory=False)

PRIOR_WARNING = """C:\etc...\interactiveshell.py:3444: DtypeWarning: 
Columns (6,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,27,36,46,48,49,53) 
have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)"""

In [13]:
# - - - - Full code - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Import the function to split data into training and test sets
from sklearn.model_selection import train_test_split

# Drop rows where the target column 'loan_status' is missing
# Missing target values can't be used for training or testing
df = df.dropna(subset=["loan_status"])

# Separate the features (input variables) 
  # from the target (label to predict)
# X will contain al columns except 'loan_status'
# y will contain only the 'loan_status' column
X = df.drop(columns="loan_status")
y = df["loan_status"]

# Split the dataset into training and testing sets
# test_size=0.2 means 20% of the data goes to the test set and
  # 80% to the training set.
# random_state=42 ensures the split is reproducible for each run.
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.2,
                                                   random_state=42)

# Print the shape (dimensions) of each dataset to confirm the split
print("Training features shape:", X_train.shape) # X_train rows, cols
print("Training labels shape:\t", y_train.shape)   # y_train rows, cols
print("Test Features shape:\t", X_test.shape)     # X_test rows, cols
print("Test labels shape:\t", y_test.shape)       # y_test rows, cols

Training features shape: (13, 75)
Training labels shape:	 (13,)
Test Features shape:	 (4, 75)
Test labels shape:	 (4,)

In [31]:
df.loan_status.value_counts(dropna=False)

NaN            237710
Fully Paid         10
Charged Off         5
Current             2
Name: loan_status, dtype: int64

In [32]:
df["loan_status"][~df["loan_status"].isna()]

0      Fully Paid
1     Charged Off
2      Fully Paid
3      Fully Paid
4         Current
5      Fully Paid
6         Current
7      Fully Paid
8     Charged Off
9     Charged Off
10     Fully Paid
11     Fully Paid
12    Charged Off
13     Fully Paid
14    Charged Off
15     Fully Paid
16     Fully Paid
Name: loan_status, dtype: object

$\uparrow~\uparrow~\uparrow$  
**My note** : Unfortunately, `loan_status` is **NaN** 99.99% of the time. There are onyl 17 rows with a populated `loan_status`. This means, the usage of `df = df.dropna(subset=["loan_status"])` guts our dataset. We'll have to do something else if we want anything useful to model.

Using `df.loan_status.value_counts(dropna=False)` before any drops, we understand the true issue

```
NaN            237710
Fully Paid         10
Charged Off         5
Current             2
Name: loan_status, dtype: int64
```

The total data set is 237 727 rows, but only 17 of the **loan_status** rows have a status.

<font color=blue face=Verdana>More than likely the original file was split ro somehow truncated, and this small subset was saved from an Excel spreadsheet, which forced 237K rows even though only 18 (header included) were populated</font>